# Example regions in the config.yml
regions:
  region1:
    world: "world"
    x: 100
    y: 64
    z: 200
    msg: "§l§eYou entered Region 1"
  region2:
    world: "world"
    x: 50
    y: 70
    z: 150
    msg: "§l§eYou entered Region 2"
  region3:
    world: "world_nether"
    x: -30
    y: 40
    z: 10
    msg: "§l§eYou entered the Nether Region"


# Add more regions as needed
